language: csharp
#mono:
#  - latest
#  - 4.8.0
os:
 - osx
 - linux
compiler:
  - clang
  - gcc
# Build steps
# if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp /Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.a ./ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp /usr/lib/libmonosgen-2.0.a ./ ; fi
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/Library/Frameworks/Mono.framework/lib/pkgconfig ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_C_FLAGS="-m64" .. ; fi
  - cmake ..
  - make
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_C_FLAGS="-m32" .. && make ; fi
  
