language: csharp
#mono:
#  - latest
#  - 4.8.0
os:
 - osx
 - linux
compiler:
  - clang
  - gcc
services:
  - docker
# Build steps
# if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp /Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.a ./ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp /usr/lib/libmonosgen-2.0.a ./ ; fi
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/Library/Frameworks/Mono.framework/lib/pkgconfig ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_C_FLAGS="-m64" .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker -i -v \"${PWD}:/MonoKickstart\" daald/ubuntu32:trusty /bin/bash -c "linux32 --32bit i386 ls -la" ; fi
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DCMAKE_C_FLAGS="-m32" .. && make ; fi
  - make
  
