language: csharp
#mono:
#  - latest
#  - 4.8.0
os:
 - osx
 - linux
compiler:
  - clang
  - gcc
services:
  - docker
# Build steps
# if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp /Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.a ./ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/Library/Frameworks/Mono.framework/lib/pkgconfig ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./buildmcs ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -i -v "${PWD}:/Source" ubuntu:12.04 /bin/bash -c "/Source/buildlinux64" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -i -v "${PWD}:/Source" erwinchang/ubuntu-12.04-32bit /bin/bash -c "linux32 --32bit i386 /Source/buildlinux32" ; fi

